version: '3'

services:

  app:
    build:
      context: .
    command: npm run dev
    container_name: node-app
    entrypoint: wait-for mongo-db:27017 -t 30 -- docker-entrypoint.sh
    networks:
      - app-network
    #volumes:
    #  - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    ports:
      - "3000:3000"
    environment: 
      GITHUB_CLIENT_ID: "{CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "{CLIENT_SECRET}"
      MONGODB_URI: "mongodb://mongo-db:27017"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_URL_INTERNAL: "http://localhost:3000"
      NEXTAUTH_SECRET: "{NEXT_SECRET}"
    depends_on:
      - db

  db:
    image: mongo:jammy
    container_name: mongo-db
    restart: always
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
